#!/system/bin/sh

grep -oE 'init_[0-9_]+' /vendor/etc/selinux/nonplat_sepolicy.cil | \
	uniq | \
	sort -n | \
	head -n 1 | \
	sed -E 's/.*init_([0-9]+).*/\1/g' | \
while read version;do
	setprop persist.sys.vndk $version
done

mount -o bind /system/bin/adbd /sbin/adbd
if getprop ro.hardware |grep -qiE qcom;then
	FOUND_QCOM=1
	setprop persist.sys.overlay.devinputjack true
fi
